version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  python:
    container_name: 'python'
    build:
      context: ./docker_files/python/
    volumes:
      - ..:/app
    tty: true
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: 'mongo_db'
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    environment:
      - MONGO_INITDB_DABATASE=universe
      - MONGO_INITDB_ROOT_USERNAME=unam
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - my_network

  openbabel:
      container_name: 'openbabel'
      build:
       context: ./docker_files/openbabel/
      volumes:
      - ..:/app
      tty: true
      command: python ./Orrery/babel_server.py
      networks:
      - my_network