FROM ubuntu:latest

RUN mkdir -p /app/Orrery
WORKDIR /app/Orrery

RUN apt-get update && \
    apt-get install -y wget

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /root/miniconda && \
    rm Miniconda3-latest-Linux-x86_64.sh

# Put Conda installation at the front of the PATH
ENV PATH=/root/miniconda/bin:$PATH

# Update Conda packages
RUN conda update -n base conda && \
    conda install -y -c conda-forge python=3.7 && \
    conda install -y -c conda-forge rdkit && \
    conda install -y -c openbabel openbabel && \
    conda install -y pandas requests pymongo tqdm

RUN pip install --upgrade pip \
    pybel

RUN apt-get install -y python3 python3-rdkit python3-pip



